---
iterations: 25         # The number of times to iterate over the workload.
concurrency: 5          # The number of iterations to run concurrently.
silent: false		     # Do you want command line output?
workload: "gcf:spring"   # A single iteration workload that will be executed in the order commands are provided.
